/// IRS Applicable Federal Rates by month, reviewed artifacts.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AfrRates {
    pub short_term_annual: f64,
    pub short_term_semiannual: f64,
    pub short_term_quarterly: f64,
    pub short_term_monthly: f64,
    pub mid_term_annual: f64,
    pub mid_term_semiannual: f64,
    pub mid_term_quarterly: f64,
    pub mid_term_monthly: f64,
    pub long_term_annual: f64,
    pub long_term_semiannual: f64,
    pub long_term_quarterly: f64,
    pub long_term_monthly: f64,
}

// ---------------------------------------------------------------------------
// AFR month functions (generated by pipeline)
// ---------------------------------------------------------------------------

// BEGIN AFR MONTHS

pub fn afr_2026_01() -> AfrRates {
    AfrRates {
        short_term_annual: 3.63,
        short_term_semiannual: 3.6,
        short_term_quarterly: 3.58,
        short_term_monthly: 3.57,
        mid_term_annual: 3.81,
        mid_term_semiannual: 3.77,
        mid_term_quarterly: 3.75,
        mid_term_monthly: 3.74,
        long_term_annual: 4.63,
        long_term_semiannual: 4.58,
        long_term_quarterly: 4.55,
        long_term_monthly: 4.54,
    }
}

pub fn afr_2026_02() -> AfrRates {
    AfrRates {
        short_term_annual: 3.56,
        short_term_semiannual: 3.53,
        short_term_quarterly: 3.51,
        short_term_monthly: 3.5,
        mid_term_annual: 3.86,
        mid_term_semiannual: 3.82,
        mid_term_quarterly: 3.8,
        mid_term_monthly: 3.79,
        long_term_annual: 4.7,
        long_term_semiannual: 4.65,
        long_term_quarterly: 4.62,
        long_term_monthly: 4.61,
    }
}

pub fn afr_2026_03() -> AfrRates {
    AfrRates {
        short_term_annual: 3.59,
        short_term_semiannual: 3.56,
        short_term_quarterly: 3.54,
        short_term_monthly: 3.53,
        mid_term_annual: 3.93,
        mid_term_semiannual: 3.89,
        mid_term_quarterly: 3.87,
        mid_term_monthly: 3.86,
        long_term_annual: 4.72,
        long_term_semiannual: 4.67,
        long_term_quarterly: 4.64,
        long_term_monthly: 4.63,
    }
}

// END AFR MONTHS

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn afr_2026_01_rates() {
        let r = afr_2026_01();
        assert_eq!(r.short_term_annual, 3.63);
        assert_eq!(r.short_term_semiannual, 3.6);
        assert_eq!(r.short_term_quarterly, 3.58);
        assert_eq!(r.short_term_monthly, 3.57);
        assert_eq!(r.mid_term_annual, 3.81);
        assert_eq!(r.mid_term_semiannual, 3.77);
        assert_eq!(r.mid_term_quarterly, 3.75);
        assert_eq!(r.mid_term_monthly, 3.74);
        assert_eq!(r.long_term_annual, 4.63);
        assert_eq!(r.long_term_semiannual, 4.58);
        assert_eq!(r.long_term_quarterly, 4.55);
        assert_eq!(r.long_term_monthly, 4.54);
    }

    #[test]
    fn afr_2026_02_rates() {
        let r = afr_2026_02();
        assert_eq!(r.short_term_annual, 3.56);
        assert_eq!(r.short_term_semiannual, 3.53);
        assert_eq!(r.short_term_quarterly, 3.51);
        assert_eq!(r.short_term_monthly, 3.5);
        assert_eq!(r.mid_term_annual, 3.86);
        assert_eq!(r.mid_term_semiannual, 3.82);
        assert_eq!(r.mid_term_quarterly, 3.8);
        assert_eq!(r.mid_term_monthly, 3.79);
        assert_eq!(r.long_term_annual, 4.7);
        assert_eq!(r.long_term_semiannual, 4.65);
        assert_eq!(r.long_term_quarterly, 4.62);
        assert_eq!(r.long_term_monthly, 4.61);
    }

    #[test]
    fn afr_2026_03_rates() {
        let r = afr_2026_03();
        assert_eq!(r.short_term_annual, 3.59);
        assert_eq!(r.short_term_semiannual, 3.56);
        assert_eq!(r.short_term_quarterly, 3.54);
        assert_eq!(r.short_term_monthly, 3.53);
        assert_eq!(r.mid_term_annual, 3.93);
        assert_eq!(r.mid_term_semiannual, 3.89);
        assert_eq!(r.mid_term_quarterly, 3.87);
        assert_eq!(r.mid_term_monthly, 3.86);
        assert_eq!(r.long_term_annual, 4.72);
        assert_eq!(r.long_term_semiannual, 4.67);
        assert_eq!(r.long_term_quarterly, 4.64);
        assert_eq!(r.long_term_monthly, 4.63);
    }
}
